export const EXERCISE_STANDING_PRESS = 'EXERCISE_STANDING_PRESS';
export const EXERCISE_BENCH_PRESS = 'EXERCISE_BENCH_PRESS';
export const EXERCISE_DEADLIFT = 'EXERCISE_DEADLIFT';
export const EXERCISE_SQUAT = 'EXERCISE_SQUAT';
